### ISSUE TITLE
Streaming server questions

### ISSUE THREAD

**Issue by arc95** [juliusfriedman/net7mma#2]
Hi @juliusfriedman. We need to allow users to access a web app written in ASP.NET and stream CCTV streams in their browsers. The stream formats are: RTSP, MP4, and H.264. We have a Windows Server 2016 to serve the media.

Can an ASP.NET app written in C# use net7mma to stream these CCTV media using an HTML5 `video` tag? Your help is much appreciated. Thanks

**Comment by juliusfriedman** [comment]
Hi, you can use any programming language and a combination of
XmlHttpRequest, WebSocket or otherwise to distribute the video; in the end
it will be the browser which will request the stream from said server and
client system which render the video.

Please let me know if you need additional assistance.

Sincerely,
Julius



On Mar 16, 2018 8:55 AM, "arc95" <notifications@github.com> wrote:

Hi @juliusfriedman <https://github.com/juliusfriedman>. We need to allow
users to access a web app written in ASP.NET and stream CCTV streams in
their browsers. The stream formats are: RTSP, MP4, and H.264. We have a
Windows Server 2016 to serve the media.

Can an ASP.NET app written in C# use net7mma to stream these CCTV media
using an HTML5 video tag? Your help is much appreciated. Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/juliusfriedman/net7mma/issues/2>, or mute the thread
